In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly as py
#import chart_studio.plotly
import seaborn as sns
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn.linear_model import LogisticRegression

In [3]:
ufc = pd.read_csv(os.path.join("resources/clean.csv"))
ufc.head()

,Unnamed: 0,BPrev,BStreak,B_Age,B_Height,B_ID,B_Weight,B__Round1_Grappling_Reversals_Landed,B__Round1_Grappling_Standups_Landed,B__Round1_Grappling_Submissions_Attempts,...,R__Round5_TIP_Ground Control Time,R__Round5_TIP_Ground Time,R__Round5_TIP_Guard Control Time,R__Round5_TIP_Half Guard Control Time,R__Round5_TIP_Misc. Ground Control Time,R__Round5_TIP_Mount Control Time,R__Round5_TIP_Neutral Time,R__Round5_TIP_Side Control Time,R__Round5_TIP_Standing Time,winner
0,0,1,1,23,182,2783,84,0,1,1,...,0,0,0,0,0,0,0,0,0,red
1,1,0,0,32,175,2208,70,0,0,0,...,0,0,0,0,0,0,0,0,0,blue
2,2,2,0,38,172,721,70,0,0,0,...,0,0,0,0,0,0,0,0,0,red
3,3,0,0,23,170,2825,56,0,0,0,...,0,0,0,0,0,0,0,0,0,blue
4,4,3,1,30,167,2260,61,0,0,0,...,0,0,0,0,0,0,0,0,0,red

In [4]:
#target = ufc["winner"]
#labels = [0, 1]

In [5]:
#data = ufc.drop("winner", axis=1)
#feature_names = data.columns
#data.head()

In [29]:
idealcol = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight','winner']

In [30]:
feature_cols = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight']
data = ufc[feature_cols] # Features
target = ufc.winner # Target variable

In [31]:
data

,BPrev,BStreak,B_Age,B_Height,B_Weight,RPrev,RStreak,R_Age,R_Height,R_Weight
0,1,1,23,182,84,6,1,27,187,84
1,0,0,32,175,70,0,0,29,182,70
2,2,0,38,172,70,2,0,32,177,70
3,0,0,23,170,56,6,4,25,175,56
4,3,1,30,167,61,5,2,28,170,61
...,...,...,...,...,...,...,...,...,...,...
1446,0,0,26,172,61,0,0,27,167,61
1447,2,1,26,165,56,3,0,31,162,56
1448,3,2,36,187,93,1,1,27,187,84
1449,3,1,31,167,52,4,0,34,170,56
1450,2,1,31,187,84,1,1,37,185,84

In [32]:
target

0        red
1       blue
2        red
3       blue
4        red
        ...
1446     red
1447     red
1448    blue
1449    blue
1450     red
Name: winner, Length: 1451, dtype: object

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [34]:
X_train

,BPrev,BStreak,B_Age,B_Height,B_Weight,RPrev,RStreak,R_Age,R_Height,R_Weight
486,2,0,32,172,61,2,0,32,170,61
1409,3,0,40,182,119,0,0,39,190,113
54,1,0,39,177,77,3,1,32,182,77
529,4,0,35,170,65,3,2,26,172,65
691,2,1,33,187,77,1,0,27,182,77
...,...,...,...,...,...,...,...,...,...,...
1095,4,0,30,187,84,4,0,28,185,84
1130,1,1,34,170,61,0,0,30,172,61
1294,0,0,33,180,70,0,0,31,172,70
860,0,0,30,182,70,1,0,31,172,70
1126,0,0,34,200,115,0,0,39,193,104

In [35]:
X_test

,BPrev,BStreak,B_Age,B_Height,B_Weight,RPrev,RStreak,R_Age,R_Height,R_Weight
538,0,0,23,152,52,5,0,34,170,56
754,1,0,29,180,77,2,0,34,177,70
49,2,0,31,177,70,0,0,29,177,70
1447,2,1,26,165,56,3,0,31,162,56
141,3,1,36,190,84,1,1,29,185,84
...,...,...,...,...,...,...,...,...,...,...
721,0,0,38,170,61,1,1,32,170,61
1405,0,0,30,172,70,0,0,29,177,70
1201,1,1,40,182,119,0,0,43,177,120
1376,6,2,32,180,70,8,6,38,175,70
1353,0,0,29,175,77,0,0,33,187,77

In [36]:
y_train

486     blue
1409     red
54       red
529      red
691     blue
        ...
1095     red
1130     red
1294    blue
860      red
1126     red
Name: winner, Length: 1088, dtype: object

In [37]:
y_test

538     blue
754     blue
49       red
1447     red
141      red
        ...
721     blue
1405     red
1201     red
1376     red
1353     red
Name: winner, Length: 363, dtype: object

In [57]:
from sklearn.svm import SVC 
#model = SVC(kernel='sigmoid')
model = SVC()
model

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [58]:
# Create the GridSearch estimator along with a parameter object containing the values to adjust
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10],'gamma': [0.01, 0.001, 0.0001]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [59]:
# Fit the model using the grid search estimator. 
grid.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.582, total=   0.8s
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.566, total=   0.1s
[CV] C=1, gamma=0.01 .................................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.7s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.8s remaining:    0.0s

[CV] ..................... C=1, gamma=0.01, score=0.588, total=   0.5s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.596, total=   0.1s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.597, total=   0.1s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.594, total=   0.4s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.596, total=   0.2s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.597, total=   0.6s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.597, total=   0.1s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.547, total=   0.1s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.564, total=   0.2s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.558, total=   0.1s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.629, total=   0.1s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.613, total=   0.4s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.619, total=   0.1s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.596, total=   0.1s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.597, total=   0.3s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.597, total=   0.1s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.549, total=   0.6s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.533, total=   0.1s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.525, total=   0.1s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.599, total=   0.0s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.605, total=   0.1s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.630, total=   0.1s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.596, total=   0.3s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.597, total=   0.2s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.597, total=   0.4s

[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    6.5s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [1, 5, 10], 'gamma': [0.01, 0.001, 0.0001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [60]:
print(grid.best_params_)

{'C': 5, 'gamma': 0.001}

In [61]:
print(grid.best_score_)

0.6204044117647058

In [62]:
predictions = grid.predict(X_test)

In [63]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=[ "blue", "red"]))

              precision    recall  f1-score   support

        blue       0.55      0.19      0.28       145
         red       0.62      0.90      0.74       218

    accuracy                           0.61       363
   macro avg       0.59      0.54      0.51       363
weighted avg       0.59      0.61      0.55       363