In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly as py
#import chart_studio.plotly
import seaborn as sns
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn.linear_model import LogisticRegression

In [2]:
ufc = pd.read_csv(os.path.join("resources/clean.csv"))
ufc.head()

,Unnamed: 0,BPrev,BStreak,B_Age,B_Height,B_ID,B_Weight,B__Round1_Grappling_Reversals_Landed,B__Round1_Grappling_Standups_Landed,B__Round1_Grappling_Submissions_Attempts,...,R__Round5_TIP_Ground Control Time,R__Round5_TIP_Ground Time,R__Round5_TIP_Guard Control Time,R__Round5_TIP_Half Guard Control Time,R__Round5_TIP_Misc. Ground Control Time,R__Round5_TIP_Mount Control Time,R__Round5_TIP_Neutral Time,R__Round5_TIP_Side Control Time,R__Round5_TIP_Standing Time,winner
0,0,1,1,23.0,182.0,2783,84,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,red
1,1,0,0,32.0,175.0,2208,70,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,blue
2,2,2,0,38.0,172.0,721,70,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,red
3,3,0,0,23.0,170.0,2825,56,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,blue
4,4,3,1,30.0,167.0,2260,61,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,red

In [3]:
#target = ufc["winner"]
#labels = [0, 1]

In [4]:
#data = ufc.drop("winner", axis=1)
#feature_names = data.columns
#data.head()

In [5]:
ufc = ufc[ufc.winner != 'no contest']
ufc = ufc[ufc.winner != 'draw']

In [6]:
idealcol = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight','winner']

In [7]:
feature_cols = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight']
data = ufc[feature_cols] # Features
target = ufc.winner # Target variable

In [8]:
data

,BPrev,BStreak,B_Age,B_Height,B_Weight,RPrev,RStreak,R_Age,R_Height,R_Weight
0,1,1,23.0,182.0,84,6,1,27.0,187,84
1,0,0,32.0,175.0,70,0,0,29.0,182,70
2,2,0,38.0,172.0,70,2,0,32.0,177,70
3,0,0,23.0,170.0,56,6,4,25.0,175,56
4,3,1,30.0,167.0,61,5,2,28.0,170,61
...,...,...,...,...,...,...,...,...,...,...
1472,0,0,26.0,172.0,61,0,0,27.0,167,61
1473,2,1,26.0,165.0,56,3,0,31.0,162,56
1474,3,2,36.0,187.0,93,1,1,27.0,187,84
1475,3,1,31.0,167.0,52,4,0,34.0,170,56
1476,2,1,31.0,187.0,84,1,1,37.0,185,84

In [9]:
target

0        red
1       blue
2        red
3       blue
4        red
        ...
1472     red
1473     red
1474    blue
1475    blue
1476     red
Name: winner, Length: 1451, dtype: object

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [11]:
X_train

,BPrev,BStreak,B_Age,B_Height,B_Weight,RPrev,RStreak,R_Age,R_Height,R_Weight
494,2,0,32.0,172.0,61,2,0,32.0,170,61
1435,3,0,40.0,182.0,119,0,0,39.0,190,113
55,1,0,39.0,177.0,77,3,1,32.0,182,77
537,4,0,35.0,170.0,65,3,2,26.0,172,65
705,2,1,33.0,187.0,77,1,0,27.0,182,77
...,...,...,...,...,...,...,...,...,...,...
1117,4,0,30.0,187.0,84,4,0,28.0,185,84
1153,1,1,34.0,170.0,61,0,0,30.0,172,61
1319,0,0,33.0,180.0,70,0,0,31.0,172,70
876,0,0,30.0,182.0,70,1,0,31.0,172,70
1149,0,0,34.0,200.0,115,0,0,39.0,193,104

In [12]:
X_test

,BPrev,BStreak,B_Age,B_Height,B_Weight,RPrev,RStreak,R_Age,R_Height,R_Weight
546,0,0,23.0,152.0,52,5,0,34.0,170,56
768,1,0,29.0,180.0,77,2,0,34.0,177,70
50,2,0,31.0,177.0,70,0,0,29.0,177,70
1473,2,1,26.0,165.0,56,3,0,31.0,162,56
143,3,1,36.0,190.0,84,1,1,29.0,185,84
...,...,...,...,...,...,...,...,...,...,...
735,0,0,38.0,170.0,61,1,1,32.0,170,61
1431,0,0,30.0,172.0,70,0,0,29.0,177,70
1224,1,1,40.0,182.0,119,0,0,43.0,177,120
1402,6,2,32.0,180.0,70,8,6,38.0,175,70
1379,0,0,29.0,175.0,77,0,0,33.0,187,77

In [13]:
y_train

494     blue
1435     red
55       red
537      red
705     blue
        ...
1117     red
1153     red
1319    blue
876      red
1149     red
Name: winner, Length: 1088, dtype: object

In [14]:
y_test

546     blue
768     blue
50       red
1473     red
143      red
        ...
735     blue
1431     red
1224     red
1402     red
1379     red
Name: winner, Length: 363, dtype: object

In [15]:
from sklearn.svm import SVC 
#model = SVC(kernel='sigmoid')
model = SVC()
model

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [16]:
# Create the GridSearch estimator along with a parameter object containing the values to adjust
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10],'gamma': [0.01, 0.001, 0.0001]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [17]:
# Fit the model using the grid search estimator. 
grid.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s

Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.582, total=   0.1s
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.566, total=   0.1s
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.588, total=   0.1s
[CV] C=1, gamma=0.001 ................................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.1s remaining:    0.0s

[CV] .................... C=1, gamma=0.001, score=0.596, total=   0.1s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.597, total=   0.1s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.594, total=   0.1s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.596, total=   0.1s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.597, total=   0.1s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.597, total=   0.1s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.547, total=   0.1s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.564, total=   0.2s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.558, total=   0.1s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.629, total=   0.1s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.613, total=   0.1s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.619, total=   0.1s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.596, total=   0.1s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.597, total=   0.2s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.597, total=   0.1s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.549, total=   0.2s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.533, total=   0.2s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.525, total=   0.1s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.599, total=   0.1s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.605, total=   0.1s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.630, total=   0.2s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.596, total=   0.1s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.597, total=   0.1s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.597, total=   0.1s

[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    3.4s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [1, 5, 10], 'gamma': [0.01, 0.001, 0.0001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [18]:
print(grid.best_params_)

{'C': 5, 'gamma': 0.001}

In [19]:
print(grid.best_score_)

0.6204044117647058

In [20]:
predictions = grid.predict(X_test)

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=[ "blue", "red"]))

              precision    recall  f1-score   support

        blue       0.55      0.19      0.28       145
         red       0.62      0.90      0.74       218

    accuracy                           0.61       363
   macro avg       0.59      0.54      0.51       363
weighted avg       0.59      0.61      0.55       363